// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGp4a7tNyBOnD15-pdmxbNKeewinfvs-w',
    appId: '1:894796328301:web:0169a797cbe695eea8fe64',
    messagingSenderId: '894796328301',
    projectId: 'todo-c26d4',
    authDomain: 'todo-c26d4.firebaseapp.com',
    storageBucket: 'todo-c26d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC_AbZMoWPis7yxW64IoAdvWGyUuUOQ4k',
    appId: '1:894796328301:android:5f09ccbe9ea636c0a8fe64',
    messagingSenderId: '894796328301',
    projectId: 'todo-c26d4',
    storageBucket: 'todo-c26d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwGQYpmbdbiUBPggfFpLF8zu0ET1HoEZ4',
    appId: '1:894796328301:ios:0cda26baa09a58c9a8fe64',
    messagingSenderId: '894796328301',
    projectId: 'todo-c26d4',
    storageBucket: 'todo-c26d4.appspot.com',
    iosClientId: '894796328301-0o2qcsklkotfkc9ipgrq5s1j095vnh5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwGQYpmbdbiUBPggfFpLF8zu0ET1HoEZ4',
    appId: '1:894796328301:ios:0cda26baa09a58c9a8fe64',
    messagingSenderId: '894796328301',
    projectId: 'todo-c26d4',
    storageBucket: 'todo-c26d4.appspot.com',
    iosClientId: '894796328301-0o2qcsklkotfkc9ipgrq5s1j095vnh5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGp4a7tNyBOnD15-pdmxbNKeewinfvs-w',
    appId: '1:894796328301:web:55699a383dff7ef9a8fe64',
    messagingSenderId: '894796328301',
    projectId: 'todo-c26d4',
    authDomain: 'todo-c26d4.firebaseapp.com',
    storageBucket: 'todo-c26d4.appspot.com',
  );

}